// Builds src/assets/geo.ts for the globe from two public-domain Natural Earth files:
//   node scripts/make-geo.mjs <ne_110m_land.geojson> <ne_50m_admin_0_countries.geojson>
// geo.ts holds a 1-degree land mask (360 x 180 bits, base64) and one centre point per country (ISO code -> [lat, lon]).
import { readFileSync, writeFileSync } from "node:fs";

const [landFile, countryFile] = process.argv.slice(2);
if (!landFile || !countryFile) { console.error("usage: make-geo.mjs <land.geojson> <countries.geojson>"); process.exit(1); }

const polysOf = (geom) => (geom.type === "Polygon" ? [geom.coordinates] : geom.type === "MultiPolygon" ? geom.coordinates : []);

// ---- land mask
const land = JSON.parse(readFileSync(landFile, "utf8"));
const polys = land.features.flatMap((f) => polysOf(f.geometry)).map((rings) => {
  let minX = 1e9, maxX = -1e9, minY = 1e9, maxY = -1e9;
  for (const [x, y] of rings[0]) { if (x < minX) minX = x; if (x > maxX) maxX = x; if (y < minY) minY = y; if (y > maxY) maxY = y; }
  return { rings, minX, maxX, minY, maxY };
});

function inRing(x, y, ring) {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i], [xj, yj] = ring[j];
    if ((yi > y) !== (yj > y) && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
}

const W = 360, H = 180;
const bits = new Uint8Array((W * H + 7) >> 3);
let landCells = 0;
for (let r = 0; r < H; r++) {
  const lat = 89.5 - r;
  for (let c = 0; c < W; c++) {
    const lon = -179.5 + c;
    let on = false;
    for (const p of polys) {
      if (lon < p.minX || lon > p.maxX || lat < p.minY || lat > p.maxY) continue;
      if (inRing(lon, lat, p.rings[0]) && !p.rings.slice(1).some((h) => inRing(lon, lat, h))) { on = true; break; }
    }
    if (on) { const i = r * W + c; bits[i >> 3] |= 1 << (i & 7); landCells++; }
  }
}

// ---- country centres: the middle of each country's biggest piece of land
const area = (ring) => { let a = 0; for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) a += ring[j][0] * ring[i][1] - ring[i][0] * ring[j][1]; return a / 2; };
const centre = (ring) => {
  let a = 0, cx = 0, cy = 0;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const f = ring[j][0] * ring[i][1] - ring[i][0] * ring[j][1];
    a += f; cx += (ring[j][0] + ring[i][0]) * f; cy += (ring[j][1] + ring[i][1]) * f;
  }
  a /= 2;
  return Math.abs(a) < 1e-9 ? ring[0] : [cx / (6 * a), cy / (6 * a)];
};
const countries = JSON.parse(readFileSync(countryFile, "utf8"));
const centres = {};
for (const f of countries.features) {
  const p = f.properties;
  let code = p.ISO_A2 && p.ISO_A2 !== "-99" ? p.ISO_A2 : p.ISO_A2_EH && p.ISO_A2_EH !== "-99" ? p.ISO_A2_EH : "";
  if (!code) continue;
  const pieces = polysOf(f.geometry);
  if (!pieces.length) continue;
  const biggest = pieces.reduce((best, cur) => (Math.abs(area(cur[0])) > Math.abs(area(best[0])) ? cur : best));
  const [lon, lat] = centre(biggest[0]);
  centres[code] = [Math.round(lat * 10) / 10, Math.round(lon * 10) / 10];
}

// a few countries whose biggest piece of land is not where most people would put the middle
Object.assign(centres, { AU: [-25.7, 134.5], NZ: [-41.5, 173.5] });

const out =
  "// Generated by scripts/make-geo.mjs from Natural Earth (public domain). Do not edit by hand.\n" +
  `export const LAND_W = ${W};\nexport const LAND_H = ${H};\n` +
  `export const LAND_B64 = "${Buffer.from(bits).toString("base64")}";\n` +
  `export const CENTRES: Record<string, [number, number]> = ${JSON.stringify(centres)};\n`;
writeFileSync(new URL("../src/assets/geo.ts", import.meta.url), out);
console.log(`land cells ${landCells} of ${W * H}, countries ${Object.keys(centres).length}, bytes ${out.length}`);
